### ISSUE TITLE
"Submit" button doesn't do anything

### ISSUE THREAD

**Issue by seagreen** [parsonsmatt/QuickLift#5]
![screenshot](https://cloud.githubusercontent.com/assets/1310143/12867749/e1fc9050-ccc3-11e5-9b9b-fe6e30ec211b.png)

This persists whether I'm logged in or not.

**Comment by seagreen** [comment]
Also I don't see any errors on the console when I click it, that's strange.

**Comment by parsonsmatt** [comment]
Hey, thanks for submitting an issue! I've fixed the issue on master and will deploy the change when I get home.
